### ISSUE TITLE
Create a prototype design in Figma

### ISSUE THREAD

**Issue by XaydarovMarufjon** [XaydarovMarufjon/find-my-coworking#6]
**Task description**
Create a basic design for home page and co-working pages

Acceptance criteria

- [x]  Find inspiration online
- [ ]  Create a basic home page design
- [x]  Create a basic co-working page design

**Comment by XaydarovMarufjon** [comment]
coworking page figma topildi ustida ishlanmoqda
